name: CI/CD Workflow

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: "getohub"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: "Build and Push Docker Image"
        uses: docker/build-push-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          push: true
          context: Dockerfiles/docker-node
          tags: "getohub/node:${{ github.ref_name }}"